dependencies:
  build:
    - node:12.16.3

build_targets:
  - name: default
    commands:
      - npm install
      - npm run compile

  - name: test
    container:
      image: yourbase/yb_ubuntu:18.04
    commands:
      - apt-get update
      - apt-get install -y --no-install-recommends libgtk-3-0 xvfb libxtst6 libnss3 libxss1 libasound2 libsecret-1-0 libgbm1
      - npm install
      - npm run test-xvfb

  - name: package
    commands:
      - npm install
      - npx vsce package

  - name: publish
    commands:
      - npm install
      - bash publish.sh

ci:
  builds:
    - name: test
      build_target: test
    - name: publish
      build_target: publish
      when: tagged IS true

